# Exercícios Numpy Array

* Atributos retornam algo que a array já possui, é como se apenas perguntássemos sobre algum atributo da array.
* Métodos são funções, aplicam alguma transformação à array

In [64]:
#Crie um vetor de 100 elementos usando a função linspace
import numpy as np
a = np.linspace(0,100,100)

In [65]:
#imprimir o shape da array
a.shape

(100,)

In [66]:
#Transforme em um array bidimensional (10x10)
a = a.reshape(10,10)
a.shape

(10, 10)

In [67]:
#Qual a posição do maior valor? 
a.argmax()

99

In [68]:
#Some todos os elementos
soma = a.sum()
soma

5000.000000000001

In [69]:
#Some todos os elementos linha a linha
somalinha = a.sum(axis=0)
somalinha

array([454.54545455, 464.64646465, 474.74747475, 484.84848485,
       494.94949495, 505.05050505, 515.15151515, 525.25252525,
       535.35353535, 545.45454545])

In [70]:
#Transforme a matriz em um vetor novamente
a = a.reshape(100,)
a.shape

(100,)

## Exercício 2
Crie uma função que recebe uma matriz de convariância e retorna a matriz C de krigagem ordinária

In [109]:
#Matriz de covariância
cov = np.array([[1, 10, 11],
               [10, 1, 12],
               [13, 11, 1]])

In [110]:
#Função que retornará a matriz e krigagem ordinária
def mat_c(cov):
    cov_shape = cov.shape
    C_shape = (cov_shape[0]+1, cov_shape[1]+1)
    C = np.ones(C_shape)
    C[C_shape[0]-1, C_shape[1]-1] = 0
    C[:-1,:-1] = cov
    return C

In [111]:
#Chamando a função
mat_c(cov)

array([[ 1., 10., 11.,  1.],
       [10.,  1., 12.,  1.],
       [13., 11.,  1.,  1.],
       [ 1.,  1.,  1.,  0.]])

## Exercício 3
Itere e printe cada item de um array que a função do exercício anterior retornou

In [119]:
C = mat_c(cov)
for i in C.flat: #Usando o C.flat itera-se elemento a elemento, na matriz C inteira
    print(i)

1.0
10.0
11.0
1.0
10.0
1.0
12.0
1.0
13.0
11.0
1.0
1.0
1.0
1.0
1.0
0.0


# Exercício 4

In [183]:
#Crie um vetor que seja uma sequencia de dez numeros
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
#Crie outro vetor que seja outra sequencia de dez numeros
b = np.arange(11,21,1)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [185]:
#Empilhe os dois vetores em uma array bidimensional
c = np.vstack((a,b))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [186]:
#Imprima o shape
c.shape

(2, 10)

In [144]:
#Insira uma linha de apenas zeros
z = np.zeros(10,)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [156]:
z = z.reshape(1,10)

In [157]:
d = np.vstack((c,z))
d

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [167]:
d = np.append(c, z, 0)
d

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [187]:
#Insira uma linha de uns na segunda posição
o = np.ones((1,10))
f = np.insert(d, 1, o, axis=0)
f

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

# Exercicio 7

In [202]:
ferro = np.random.random(10)
ferro


array([0.3837658 , 0.39041626, 0.70756456, 0.49703411, 0.71068121,
       0.36170987, 0.51676607, 0.05281191, 0.19634888, 0.5746547 ])

In [203]:
ferro.var()

0.03931607876429747

In [204]:
ferro.mean()

0.43917533685282295

In [206]:
filtro = ferro > np.mean(ferro)
ferro[filtro]

array([0.70756456, 0.49703411, 0.71068121, 0.51676607, 0.5746547 ])

In [207]:
p80 = np.percentile?

In [209]:
p80 = np.percentile(ferro, 80)
p80

0.6012366724565652

In [210]:
fecap = np.where(ferro<p80, ferro, p80)

In [211]:
fecap

array([0.3837658 , 0.39041626, 0.60123667, 0.49703411, 0.60123667,
       0.36170987, 0.51676607, 0.05281191, 0.19634888, 0.5746547 ])

# Exercício das eleições

In [217]:
def eleicao(candidatos, num_votos):
    votos = np.random.choice(candidatos, num_votos)
    resultado = {}
    for c in candidatos:
        num_votos = votos.tolist().count(c)
        resultado[c] = num_votos
    return resultado

In [218]:
candidatos = ['Led Zeppelin', 'Pink Floyd', 'AC/DC', 'Rolling Stones', 'Deep Purple']
n = 10000

In [219]:
eleicao(candidatos, n)

{'Led Zeppelin': 1965,
 'Pink Floyd': 2019,
 'AC/DC': 2057,
 'Rolling Stones': 1942,
 'Deep Purple': 2017}

# Exercicio

In [273]:
import itertools
range_x = np.linspace(0, 100, 10)
range_y = np.linspace(0, 100, 10)

coords = [] #Criando uma lista que armazenará todas as possíveis combinacoes de coordenadas
for x,y in itertools.product(range_x, range_y): #Funcao mágica que vem do além 
    coords.append([x,y])
coords = np.array(coords) #Transformando a lista coords em uma Numpy array

In [278]:
#Criando uma numpy array com os valores aleatórios de teores em uma distribuição normal 
teores = np.random.randn(100,1) #As dimensões da array teores são 100x1

In [280]:
#Criando o dataset, que terá dimensões 100x3, através da funçào "empilhamento"
dataset = np.hstack((coords_array, teores))

In [281]:
dataset

array([[ 0.00000000e+00,  0.00000000e+00, -6.73239817e-01],
       [ 0.00000000e+00,  1.11111111e+01, -2.01910835e+00],
       [ 0.00000000e+00,  2.22222222e+01,  1.61893490e-01],
       [ 0.00000000e+00,  3.33333333e+01,  2.03807827e-02],
       [ 0.00000000e+00,  4.44444444e+01,  9.07422970e-02],
       [ 0.00000000e+00,  5.55555556e+01,  8.94739657e-01],
       [ 0.00000000e+00,  6.66666667e+01, -4.70662483e-01],
       [ 0.00000000e+00,  7.77777778e+01,  5.14365733e-02],
       [ 0.00000000e+00,  8.88888889e+01, -6.61897260e-01],
       [ 0.00000000e+00,  1.00000000e+02,  2.14574613e-02],
       [ 1.11111111e+01,  0.00000000e+00, -1.50339922e-01],
       [ 1.11111111e+01,  1.11111111e+01,  5.37777948e-02],
       [ 1.11111111e+01,  2.22222222e+01,  1.03563278e+00],
       [ 1.11111111e+01,  3.33333333e+01, -3.38768907e-02],
       [ 1.11111111e+01,  4.44444444e+01, -1.44280787e+00],
       [ 1.11111111e+01,  5.55555556e+01,  8.74785378e-01],
       [ 1.11111111e+01,  6.66666667e+01