# Exercicio Waker Lake

In [2]:
import pandas as pd
import numpy as np

In [2]:
#Importando data set
walker = pd.read_csv('data\walker.csv')
walker.head(3)

Id     X     Y      V      U    T
0  1.0  11.0   8.0    0.0 -999.0  2.0
1  2.0   8.0  30.0    0.0 -999.0  2.0
2  3.0   9.0  48.0  224.4 -999.0  2.0

In [3]:
import grids_2d
import numpy as np

In [4]:
grid_est = grids_2d.Grid(0,0,100,100,5,5) #Instanciando o objeto grid_est

In [5]:
grid_est.auto_grid(coords_x=walker['X'],coords_y=walker['Y'],sx=5,sy=5) #Aplicando o método auto_grid ao objeto grid_est

array([[  8.,   8.],
       [  8.,  13.],
       [  8.,  18.],
       ...,
       [243., 273.],
       [243., 278.],
       [243., 283.]])

In [6]:
#Importando o interpolador 
from scipy.interpolate import Rbf

In [7]:
rbfi = Rbf(walker.X,
           walker.Y,
           np.zeros(len(walker.Y)),
           walker.V,
           function='multiquadric',
           epslon=10000)

In [ ]:
def add_coord(grid):
    ox = grid['ox']
    oy = grid['oy']
    nx = grid['nx']
    ny = grid['ny']
    sx = grid['sx']
    sy = grid['sy']
    
    x_coords = np.arange(ox, ox+nx*sx, sx)
    y_coords = np.arange(oy, oy+ny*sy, sy)
    
    coords_array = []
    for x, y in itertools.product(x_coords, y_coords):
        coords_array.append([x,y])
        
    return np.array(coords_array)

In [8]:
coords = add_coord(grid_est)

NameError: name 'add_coord' is not defined

In [ ]:
results = rbfi(coords.T[0],coords.T[1], np.zeros(len(coors.T[0])))

# Exercício KDTree

In [1]:
from scipy.spatial import KDTree

In [16]:
x = np.random.randint(0,10,20) #Criando coordenadas X
y = np.random.randint(0,10,20) #Criando coordenadas Y
grade = np.random.randn(20) #Criando teores
samples_coords = np.vstack((x,y)).T #Criando uma numpy array 20x2 com as coordenadas
n = range(20) #Não sei o que é isso

In [18]:
samples_kdtree = KDTree(samples_coords)

In [22]:
point = np.array([[5,5]]) #Coordenadas do ponto a ser "investigado"

In [25]:
neighs = samples_kdtree.query_ball_point(point, r=3)

In [26]:
dist, neighs = samples_kdtree.query(point, k=5)

In [27]:
dist, neighs

(array([[1.        , 2.        , 2.23606798, 3.        , 4.        ]]),
 array([[14, 17, 10,  4, 12]]))

# Exercício da reta de regressão

* Calcule os parâmetros da regressão entre U e V (walker lake);
* Crie uma função que recebe um np.array de valores x e retorna os valores regredidos y;
* Plote o scatterplot entre U e V e a reta de regressão linear em um mesmo plot.

In [75]:
from scipy import stats

In [76]:
wl = pd.read_csv('data\walker.csv', na_values=-999) #Informa que os valores "absent" são os "-999"

In [77]:
wl_isot = walker.dropna() #Remove os valores absent

In [78]:
slope, intercept, r_value, p_value, std_err = stats.linregress(wl_isot['X'], wl_isot['Y'])

In [79]:
wl_array = wl.values

In [89]:
filtro_u = np.isnan(wl.U) #filtrando, o resultado dá um array com valores booleanos
wl[filtro_u].V #Valores de V onde o valor da array é True
imput_u = slope*wl[filtro_u].V + intercept #Cálculo de um novo u onde o filtro é True
imput_u

0      132.802341
1      132.802341
2      138.694131
3      144.207838
4      143.622335
5      148.219717
6      137.851322
7      133.624146
8      143.002700
9      137.386595
10     137.733171
11     134.957938
12     134.931683
13     136.065931
14     137.738422
15     133.555881
16     134.852915
17     140.471645
18     156.306487
19     151.249630
20     145.675535
21     136.375749
22     141.598017
23     140.075184
24     138.213651
25     133.445607
26     138.003605
27     134.385563
28     141.009888
29     139.127351
          ...    
165    149.017892
166    143.984665
167    140.566166
168    138.707259
169    133.634649
170    142.711261
171    141.553382
172    142.018109
173    132.802341
174    136.415132
175    144.648935
176    149.592892
177    135.950406
178    133.516498
179    132.857478
180    137.205430
181    136.682941
182    144.425761
183    145.607270
184    132.802341
185    133.542754
186    132.802341
187    133.282822
188    139.794247
189    145